# PYTHON FOR DATA ANALYSIS TRAINING

## ASSIGNMENT ON NUMPY AND PANDAS

## Numpy:

1. What is NumPy, and what is its primary purpose in Python programming?

In [1]:
# Numpy, or 'Numerical Python' is a Python library used to perform numerical operations, especially dealing with arrays, single-dimensional, multi-dimensional arrays, and matrices.

2. Explain the concept of slicing in NumPy arrays with an example.

In [2]:
# In English, Slicing means cutting something into pieces. Meanwhile, in Numpy/Python. 
# We sliced / selecting a subset of elements from an array so we can access any value from that array as per our need using the index or range.

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[5:]

array([ 6,  7,  8,  9, 10])

3. What are some commonly used methods and attributes in NumPy arrays?
Provide examples for each.

In [7]:
# Thou Numpy as so many methods and attributes but the most used ones are highlighted below: 


# Methods:

# 1. array
# 2. arange
# 3. ones
# 4. zeros
# 5. concatenate


# Attributes:

# 1. size
# 2. ndim
# 3. dtype


4. How do you create a NumPy array filled with zeros? Can you create a NumPy
array filled with ones? Provide code examples for both.

In [8]:
# Yes, we can create a NumPy array filled with zeros and filled with ones by using underneath methods.

In [9]:
import numpy as np

In [10]:
np.zeros(10) # NumPy array filled with zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10) # NumPy array filled with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

5. Describe a scenario where you might use NumPy in a data analysis or scien-
tific computing task.

In [12]:
# We use numpy mostly with numerical computing task such as sales we made. Making it easier to understand sales trends and performance.

## Pandas:

1. What is Pandas, and what role does it play in data analysis with Python?

In [13]:
# Pandas is a Python library used to read and perform various operations on data, particularly dealing with dataframes and datasets. It helps data analyst to analyze data in more effective way.

2. Explain the concept of a Pandas Series. How is it different from a NumPy ar-ray?

In [14]:
# Pandas Series deals with one-dimensional array. Numpy array is good in holding data of same type whereas Pandas Series is good for holding data of any type. 

import pandas as pd

pd.Series(range(10)) 

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

3. How do you create a DataFrame in Pandas? Provide an example.

In [15]:
df = pd.DataFrame({

    'Name': ['Abdullah', 'Noah', 'Ishmael'],
    'Marks' : [84, 91, 90]
    
    
})

df # This is our DataFrame.

Name  Marks
0  Abdullah     84
1      Noah     91
2   Ishmael     90

4. What are some common operations you can perform on a Pandas Data-
Frame?

In [16]:
# Common operations you can perform on a Pandas DataFrame:

# 1. Reading our data

# 2. EDA (Manipulating or playing with our data + Cleaning our data)

# 3. Analyzing Relationship in our data

# 4. Extract Insights from our data

# 5. Visualizing our data

5. Describe a situation where you might use Pandas to analyze and manipulate
tabular data.

In [17]:
# We use pandas mostly working with tabular data such as which product category makes the best sales in which region.

In [18]:
# Done